### ISSUE TITLE
Buttons argument in alert should be an array

### ISSUE THREAD

**Issue by leosuncin** [bradtraversy/react_native_shopping_list#1]
The third argument of `alert` should be an array:

https://github.com/bradtraversy/react_native_shopping_list/blob/a9fab7a8b5891b9d549ba3f9fc4301b7bebee5da/App.js#L24

The correct one would be:

```javascript
Alert.alert('Error', 'Please enter an item', [{text: 'OK'}]);
```

If not React Native shows an error on click
![screen](https://user-images.githubusercontent.com/4307697/73771039-25c0e180-4743-11ea-95d1-c6f5d94f353b.png)

See the docs example

https://facebook.github.io/react-native/docs/alert

**Comment by Dor-Sloim** [comment]
@leosuncin Thank you for your comment, you helped me, as i'm new to react native.
